services:

  mongo:
    restart: always
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - /data/db/mongo
    ports:
      - "27017:27017"

  redis:
    image: redis
    volumes:
      - /data/db/redis
    ports:
      - "6379:6379"